defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "routes"
    values:
      layout: "route"
  -
    scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
      sitemap: false

collections:
  features:
    output: true
    permalink: /features/:path.geojson
  routes:
    output: true
    permalink: /:path:output_ext

# FIXME these keys are registered to Peter Robins; should be changed
apikeys:
    bing: "Ar0NqGYN0lECfmYJcKI0JQPmv2gZ_ISK-0y-ti9Wz1jOjtv7hZD3nqLV9j3an-Hi"
    ignf: "npny9gfewgnljgyzr3ci041f"
    mapbox: "pk.eyJ1IjoicHdyIiwiYSI6Il91MVVLWTQifQ.1YZ2WV0YGPCd2H9PIODhBA"
    os: "47DE407BC33880F8E0405F0AF0607930"

url: "https://pilgrimdb.github.io"

kramdown:
  input: GFM

# plug-ins
gems:
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - contributing.md
    - readme.md
    - CNAME
